services:
  - type: web
    name: aembot
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    healthCheckPath: /healthz
    envVars:
      - key: BOT_TOKEN
        sync: true
      - key: GUILD_ID
        sync: true
      - key: DATA_DIR
        sync: true
      - key: ANNOUNCE_CHANNEL_ID
        sync: true
      - key: ANNOUNCE_ENABLED
        sync: true
      - key: GAME_CUTOVER_UTC
        sync: true
      - key: THRESHOLD
        sync: true
      - key: AUTO_DRAW_D
        sync: true
      - key: AUTO_DRAW_W
        sync: true
      - key: AUTO_VS_REMINDER
        sync: true
      - key: AUTO_TRAIN_POST
        sync: true
      - key: ROLE_ADMIN
        sync: true
      - key: ROLE_OFFICIAL
        sync: true
      - key: MENTION_URGENT
        sync: true
