services:
  - type: worker
    name: aembot-worker
    env: python
    plan: free
    region: oregon   # cámbialo si prefieres otra región
    buildCommand: |
      pip install --upgrade pip && pip install -r requirements.txt
    startCommand: |
      python -m src.main
    envVars:
      # --- Discord ---
      - key: BOT_TOKEN
        sync: false    # para no subir el token al repo, lo metes manualmente en Render
      - key: GUILD_ID
        value: "1323744094832558111"

      # --- Data dir ---
      - key: DATA_DIR
        value: "/var/data"   # más seguro que ./data (persistente en Render)

      # --- Roles ---
      - key: ROLE_ADMIN
        value: "Admin,R5,R4,R4 Spanish,R4 Portuguese"
      - key: ROLE_OFFICIAL
        value: "R5,R4,R4 Spanish,R4 Portuguese"

      # --- Announcements ---
      - key: ANNOUNCE_CHANNEL_ID
        value: "1360290285585961241"
      - key: ANNOUNCE_ENABLED
        value: "true"

      # --- Game timing ---
      - key: GAME_CUTOVER_UTC
        value: "2"

      # --- VS rules ---
      - key: THRESHOLD
        value: "7200000"

      # --- Automation toggles ---
      - key: AUTO_DRAW_D
        value: "true"
      - key: AUTO_DRAW_W
        value: "true"
      - key: AUTO_VS_REMINDER
        value: "true"
      - key: AUTO_TRAIN_POST
        value: "true"

      # --- Mentions urgent ---
      - key: MENTION_URGENT
        value: "<@&1323747046947033223> <@&1323747169429094560>"
